// Character → English gloss dictionary for the Dao De Jing.
// Compact: 1–3 senses per char, classical-leaning where it matters.
window.DDJ_DICT = {
  "一":"one; unity; the One",
  "丈":"adult; ten-foot length; husband (大丈夫: great man)",
  "三":"three",
  "上":"above; high; superior; ascend",
  "下":"below; low; descend; subordinate",
  "不":"not; no",
  "且":"moreover; and; about to",
  "並":"together; side by side; simultaneously",
  "中":"middle; center; within; the mean",
  "主":"master; ruler; host; lord",
  "乃":"then; thus; therefore; namely",
  "久":"long-lasting; enduring",
  "之":"(possessive 'of'); him/her/it; (subordinator)",
  "乎":"(question/exclamation particle); in; at",
  "乘":"ride; chariot (a state of 10,000 chariots = a kingdom)",
  "九":"nine",
  "也":"(sentence-final assertion particle)",
  "亂":"chaos; disorder; rebellion",
  "事":"affair; matter; serve; engage in",
  "二":"two",
  "云":"say; speak (often introducing a quotation)",
  "五":"five",
  "亡":"perish; lose; flee; die",
  "交":"meet; mix; intersect; converge",
  "亦":"also; likewise",
  "享":"enjoy; feast; offer (sacrifice)",
  "亭":"shelter; pavilion; to nurture (here: 'establish')",
  "人":"person; people; man",
  "什":"ten (of); group of ten",
  "仁":"benevolence; humaneness; goodness",
  "今":"now; today; the present",
  "介":"firm; resolute; isolated; lie between",
  "代":"replace; substitute; generation; era",
  "令":"order; command; cause to",
  "以":"by means of; with; to use; because of",
  "企":"stand on tiptoe; long for; aspire",
  "伎":"skill; craft; trick; artifice",
  "伏":"crouch; hide; lurk; lie low",
  "伐":"attack; strike; boast; cut down",
  "伯":"eldest; chief; senior (here: 'hundreds')",
  "似":"resemble; seem like; as if",
  "佐":"assist; help (a ruler)",
  "何":"what; how; why; which",
  "作":"do; make; arise; act; produce",
  "佳":"fine; excellent; auspicious",
  "使":"cause; send; if; envoy",
  "來":"come; arrive; future",
  "侮":"insult; despise; treat with contempt",
  "侯":"feudal lord; marquis",
  "俗":"common; vulgar; customary; the ordinary",
  "保":"protect; preserve; guard",
  "信":"trust; faith; sincere; truthful",
  "修":"cultivate; refine; repair; practice",
  "倉":"granary; storehouse",
  "倍":"double; multiply; -fold",
  "倚":"lean on; depend on; rest against",
  "偏":"partial; biased; lean; deputy",
  "偷":"steal; furtive; furtively; superficial",
  "偽":"false; sham; artificial; hypocrisy",
  "傷":"wound; injure; harm",
  "傾":"tilt; lean; overturn; incline toward",
  "儉":"thrift; frugality; restraint",
  "儼":"solemn; dignified; reverent",
  "儽":"weary; listless; exhausted (儽儽)",
  "兆":"omen; sign; portent; trillion",
  "先":"first; before; ahead; precede",
  "光":"light; brightness; radiance",
  "克":"overcome; conquer; be able",
  "兌":"open (esp. mouth/orifice); exchange; trigram for marsh",
  "免":"avoid; escape; exempt",
  "兑":"open (orifice); same as 兌 (variant)",
  "兒":"child; infant; son",
  "兕":"wild buffalo; rhinoceros",
  "入":"enter; go in; submit",
  "全":"whole; complete; entire; preserve",
  "兩":"two; both; pair",
  "公":"public; impartial; duke; common",
  "六":"six",
  "兮":"(rhythmic/emphatic particle, ~'oh!')",
  "共":"together; share; common",
  "兵":"weapon; soldier; military; war",
  "其":"his/her/its/their; that; perhaps",
  "兼":"combine; both; doubly; annex",
  "冥":"dark; obscure; deep; mysterious",
  "冬":"winter",
  "冰":"ice",
  "凶":"calamity; ominous; ill-fated; fierce",
  "出":"go out; emerge; produce",
  "刃":"blade; edge of a weapon",
  "分":"divide; part; portion; fate",
  "利":"benefit; sharp; profit; advantage",
  "制":"control; regulate; institution; restrain",
  "則":"then; rule; standard; in that case",
  "前":"front; before; previous",
  "剛":"hard; firm; just (now)",
  "割":"cut; sever; carve",
  "劌":"wound; cut; injure (with a sharp edge)",
  "劍":"sword",
  "力":"strength; force; power",
  "功":"merit; achievement; meritorious work",
  "加":"add; impose upon; increase",
  "勇":"courage; bravery; boldness",
  "動":"move; act; movement; stir",
  "勝":"overcome; conquer; surpass; victory",
  "勢":"force; circumstance; momentum; power",
  "勤":"diligent; toil; exhaust oneself",
  "勿":"do not; without",
  "化":"transform; change; convert",
  "匠":"craftsman; artisan; carpenter",
  "十":"ten",
  "千":"thousand",
  "博":"broad; extensive; learned; gamble",
  "卻":"yet; but; reject; step back",
  "厚":"thick; generous; substantial; profound",
  "厭":"satiated; weary of; satisfied; loathe",
  "去":"depart; remove; discard; go",
  "又":"again; also; moreover",
  "及":"reach; arrive at; and; up to",
  "反":"return; reverse; contrary; opposite",
  "取":"take; seize; get; receive",
  "受":"receive; accept; bear",
  "口":"mouth; opening",
  "古":"ancient; old; antiquity",
  "召":"summon; call",
  "可":"may; can; permit; -able",
  "右":"right (side); honored side (in mourning rites)",
  "司":"manage; preside; office",
  "各":"each; every; respectively",
  "合":"unite; close; fit together",
  "吉":"auspicious; lucky; festive",
  "同":"same; together; uniform; agree",
  "名":"name; reputation; designation; to name",
  "君":"lord; ruler; gentleman; you",
  "含":"hold in mouth; contain; embody",
  "吹":"blow; exhale; puff",
  "吾":"I; my; me",
  "周":"go around; complete; the Zhou (dynasty)",
  "味":"taste; flavor; savor",
  "命":"command; mandate; fate; life",
  "和":"harmony; harmonize; mild; with",
  "咎":"blame; fault; calamity",
  "哀":"grief; mourn; sorrow; compassionate",
  "哉":"(exclamatory final particle, ~'!')",
  "唯":"only; alone; just",
  "善":"good; skilled at; adept; kind",
  "喪":"mourning; lose; funeral",
  "嗄":"hoarse; cracked (of voice)",
  "嗇":"sparing; frugal; husband (resources)",
  "器":"vessel; instrument; capacity; tool",
  "四":"four",
  "固":"firm; certainly; solid; obstinate",
  "國":"state; kingdom; country",
  "圖":"plan; chart; diagram; scheme",
  "土":"earth; soil; ground",
  "在":"at; in; located; exist",
  "地":"earth; ground; land; place",
  "均":"equal; even; uniform",
  "坐":"sit; squat (as offering)",
  "垢":"dirt; filth; disgrace",
  "埏":"knead (clay); mold",
  "域":"realm; region; territory",
  "埴":"clay (for pottery)",
  "執":"hold; grasp; cling to",
  "基":"foundation; basis; root",
  "堂":"hall; chamber; main room",
  "堅":"firm; solid; hard",
  "報":"requite; recompense; repay; report",
  "塞":"block; stop up; obstruct",
  "塵":"dust; the dusty/mundane world",
  "士":"scholar; knight; officer; gentleman",
  "壯":"strong; vigorous; in prime",
  "壽":"long life; longevity",
  "外":"outside; external; foreign",
  "多":"many; much; abundant",
  "大":"great; large; the Great",
  "天":"heaven; sky; nature",
  "太":"great; supreme; too; very",
  "夫":"(initial particle); man; husband; that",
  "央":"center; end; finish",
  "失":"lose; miss; fail",
  "夷":"level; even; barbarian; equable",
  "夸":"boast; brag; exaggerate",
  "奇":"strange; unusual; surprise (military)",
  "奈":"how; what (to do); 奈何: how can one...",
  "奉":"present; offer; serve; uphold",
  "契":"tally; covenant; engrave; agreement",
  "奢":"extravagant; lavish; excessive",
  "奧":"profound; secret; recess; mysterious",
  "奪":"seize; take by force; deprive",
  "好":"like; love; good",
  "如":"like; as; as if; if",
  "妄":"reckless; absurd; false; presumptuous",
  "妖":"abnormal; bewitching; ominous; uncanny",
  "妙":"subtle; wonderful; mysterious; exquisite",
  "妨":"hinder; obstruct; harm",
  "始":"begin; origin; commencement",
  "姓":"family name; the common people (百姓)",
  "威":"awe; majesty; dread; power",
  "嬰":"infant; babe",
  "子":"child; son; master (honorific); seed",
  "孔":"very; greatly; opening; the Master (Kong/Confucius)",
  "字":"style oneself; name; word",
  "存":"exist; preserve; survive",
  "孝":"filial piety; devotion to parents",
  "孤":"orphan; alone; solitary (ruler's self-style)",
  "孩":"infant; child; smile (as a baby)",
  "孫":"grandchild; descendant",
  "孰":"who; which; what",
  "學":"learn; study; learning",
  "守":"guard; keep; preserve; hold to",
  "安":"peace; safe; how; settle",
  "宗":"ancestor; lineage; revered; honored",
  "官":"official; office; organ (of body)",
  "定":"settle; fix; certain; stable",
  "宜":"fitting; proper; ought",
  "客":"guest; visitor; stranger",
  "室":"room; chamber; apartment",
  "宰":"master; control; preside over; butcher",
  "害":"harm; injure; calamity",
  "家":"family; household; clan",
  "容":"contain; appearance; tolerate; demeanor",
  "寂":"silent; still; lonely",
  "寄":"entrust; lodge; send",
  "富":"rich; wealth; abundant",
  "寒":"cold",
  "察":"examine; observe; investigate; scrutinizing",
  "寡":"few; widow(er); solitary (ruler's self-style)",
  "寥":"empty; vast; quiet; solitary",
  "實":"solid; substantial; fill; reality",
  "寧":"peace; rather; quiet",
  "寵":"favor; pet; dote on",
  "寶":"treasure; precious; valuable",
  "寸":"inch (the small unit of length)",
  "將":"about to; will; commander; lead",
  "專":"focus; concentrate; specialize; sole",
  "尊":"honor; revere; exalted",
  "小":"small; little; minor",
  "少":"few; little; young; lessen",
  "尚":"esteem; still; value; honor",
  "尤":"fault; blame; especially",
  "尺":"foot (unit ~30cm); ruler",
  "居":"dwell; reside; occupy; settle in",
  "屈":"bend; yield; submit; crooked",
  "層":"layer; storey; level",
  "屬":"belong to; category; subordinate",
  "川":"river; stream",
  "左":"left (side); honored side (in peace rites)",
  "巧":"clever; skillful; cunning; artful",
  "己":"self; oneself",
  "已":"stop; already; (final particle)",
  "市":"market; buy; trade",
  "希":"rare; sparse; hope for",
  "帝":"emperor; supreme deity; god",
  "師":"army; teacher; troops; master",
  "帶":"belt; gird on; carry",
  "常":"constant; ever; the constant; usual",
  "平":"level; peaceful; even; flat",
  "年":"year; age; harvest",
  "幾":"how many; almost; subtle (incipient)",
  "廉":"upright; corner; incorruptible; sharp-edged",
  "廢":"abandon; ruin; discard; fall into disuse",
  "廣":"broad; wide; vast",
  "建":"establish; set up; build",
  "弊":"worn out; defect; ruin; corruption",
  "式":"model; standard; pattern; form",
  "弓":"bow (the weapon)",
  "弗":"not (literary negation)",
  "弱":"weak; soft; yielding",
  "張":"stretch; draw (a bow); display",
  "強":"strong; force; insist; mighty",
  "彌":"more; the more; pervade; fill",
  "形":"form; shape; appear",
  "彰":"manifest; clear; distinguished",
  "彼":"that; those; the other",
  "往":"go; toward; past; in the past",
  "後":"after; behind; later",
  "徐":"slowly; gradually; calmly",
  "徑":"path; shortcut; by-way",
  "徒":"follower; mere; in vain; class",
  "得":"obtain; gain; achieve; get",
  "徙":"move; migrate; transfer",
  "從":"follow; pursue; comply with",
  "御":"govern; drive (a chariot); manage",
  "復":"return; again; repeat; recover",
  "微":"subtle; tiny; faint; minute",
  "德":"virtue; power (innate); De",
  "徹":"penetrate; thorough; tithe (10% tax)",
  "徼":"outskirts; verge; outer manifestation",
  "心":"heart; mind",
  "必":"must; certainly; necessary",
  "忌":"taboo; avoid; jealous",
  "忒":"err; deviate; mistake",
  "志":"will; intent; ambition; aspiration",
  "忠":"loyal; faithful; devoted",
  "忽":"abrupt; sudden; ignore; indistinct",
  "怒":"anger; rage; wrath",
  "怕":"fear; be afraid; perhaps (also: still, quiet)",
  "怨":"resent; grudge; hatred; enmity",
  "恃":"rely on; depend on; presume on",
  "恍":"dim; indistinct; in a trance",
  "恐":"fear; dread; afraid",
  "恢":"vast; expand; wide-meshed",
  "恬":"tranquil; calm; placid; indifferent",
  "悠":"distant; leisurely; far-off; carefree",
  "患":"trouble; calamity; worry; affliction",
  "悲":"grief; sorrow; sad",
  "悶":"depressed; obscure; muddled; stuffy",
  "惑":"confused; doubt; deluded",
  "惚":"vague; indistinct; in a trance",
  "惡":"evil; ugly; hate; what?",
  "愈":"more and more; recover; better",
  "愚":"foolish; ignorant; (humble) I",
  "愛":"love; cherish; spare (be sparing with)",
  "慈":"compassion; loving-kindness; maternal love",
  "慎":"careful; cautious; prudent",
  "慧":"wisdom; cleverness; shrewdness",
  "憂":"worry; sorrow; trouble",
  "應":"respond; answer; ought; should",
  "懷":"embrace; cherish; bosom; harbor",
  "懼":"fear; dread",
  "戎":"army; weapons; war; military",
  "成":"complete; accomplish; become",
  "我":"I; me; my",
  "或":"perhaps; some; or",
  "戰":"war; battle; fight",
  "戶":"door; household",
  "所":"place; (passive marker); that which",
  "手":"hand",
  "扔":"throw; pull; drag",
  "抑":"press down; restrain; or",
  "投":"throw; cast; thrust",
  "抗":"resist; raise; oppose",
  "抱":"embrace; hold; cherish",
  "拔":"pull up; uproot; pluck",
  "拙":"clumsy; awkward; humble",
  "拱":"clasp hands; encircle; arms-full (拱璧: jade disk)",
  "持":"hold; grasp; maintain",
  "挫":"blunt; subdue; thwart",
  "推":"push; promote; defer to",
  "措":"place; put; lay aside",
  "握":"grasp; hold firmly; fistful",
  "揣":"feel; estimate; pound (sharpen by pounding)",
  "損":"diminish; lose; reduce; harm",
  "搏":"strike; grasp; seize; pounce",
  "據":"seize; rely on; according to",
  "攘":"bare (the arm); seize; ward off",
  "攝":"manage; take in; absorb; nourish",
  "攫":"grab; snatch; bird-of-prey's seizing",
  "改":"change; alter; reform",
  "攻":"attack; assault",
  "政":"government; political affairs",
  "故":"therefore; cause; old; reason",
  "救":"save; rescue; help",
  "敗":"defeat; spoil; fail; ruin",
  "教":"teach; instruction; doctrine",
  "敢":"dare; venture",
  "散":"scatter; disperse; loose",
  "敦":"sincere; simple; honest; substantial",
  "敵":"enemy; opponent; match",
  "數":"number; count; frequent",
  "文":"refined; pattern; writing; civil",
  "斯":"this; thus; then; hence",
  "新":"new; fresh; renew",
  "斲":"chop; hew; carve (wood)",
  "方":"square; direction; method; just (now)",
  "於":"in; at; than; from; by",
  "施":"bestow; act; carry out; spread",
  "既":"already; since; once",
  "日":"sun; day",
  "早":"early; soon",
  "明":"bright; clear; intelligent; clarity",
  "昏":"dusk; benighted; confused; dim",
  "易":"easy; change; exchange",
  "昔":"former; in the past; of old",
  "春":"spring (season)",
  "昧":"obscure; dim; hidden",
  "昭":"bright; clear; obvious; illustrious",
  "是":"this; right; correct; (copula 'be')",
  "時":"time; season; timely",
  "晚":"late; evening; toward the end",
  "普":"universal; widespread",
  "智":"wisdom; cleverness; cunning",
  "曠":"vast; empty; expansive",
  "曰":"say; call; be called",
  "曲":"crooked; bent; partial; tune",
  "有":"have; exist; being",
  "服":"submit; obey; clothe; service",
  "望":"gaze; hope; look toward",
  "朝":"morning; dynasty; court; toward",
  "木":"tree; wood",
  "未":"not yet; eighth Earthly Branch",
  "末":"tip; end; trifling",
  "本":"root; origin; basis",
  "枉":"crooked; bent; wrong",
  "果":"fruit; result; decisively; truly",
  "枯":"withered; dry; dead (of plants)",
  "柔":"soft; pliant; supple; gentle",
  "柢":"root (taproot); foundation",
  "根":"root; source; foundation",
  "梁":"beam; bridge; strong-beamed (here: forceful)",
  "棄":"discard; abandon; reject",
  "棘":"thorn; bramble",
  "楗":"bolt (for a door); latch",
  "極":"utmost; extreme; ridgepole; the ultimate",
  "榮":"glory; flourish; honor",
  "槁":"withered; dry; dead (wood)",
  "樂":"joy; music; delight in",
  "樸":"uncarved block; simple; plain; the unhewn",
  "橐":"bellows; sack; tube (橐籥: bellows-pipe)",
  "次":"next; order; second; sequence",
  "欲":"desire; want; wish",
  "歇":"rest; cease; stop",
  "歔":"sigh; exhale slowly",
  "歙":"draw in (breath); contract; harmonize",
  "止":"stop; halt; cease; restrain",
  "正":"upright; correct; rectify; just",
  "此":"this",
  "武":"martial; military; valor",
  "歸":"return; revert; submit to",
  "死":"die; death",
  "殃":"calamity; disaster; misfortune",
  "殆":"peril; danger; almost",
  "殺":"kill; slaughter",
  "母":"mother; the source",
  "毒":"poison; harm; intense; ripen (here: 'mature')",
  "比":"compare; like; close to",
  "毫":"tip of a hair; fine hair; the minute",
  "民":"people; populace; subjects",
  "氣":"breath; qi; vital energy",
  "水":"water",
  "求":"seek; request; pursue",
  "汎":"vast; floating; overflowing (=泛)",
  "江":"river (esp. the Yangtze); great river",
  "沌":"chaotic; muddled (沌沌)",
  "沒":"sink; perish; die; without",
  "沖":"empty; pour; surge; mild",
  "治":"govern; rule; order; cure",
  "況":"situation; condition; how much more",
  "法":"law; method; model; pattern",
  "泣":"weep; sob",
  "注":"pour; focus on; attend to",
  "泮":"melt; dissolve; thaw",
  "泰":"great; peaceful; extreme; excessive",
  "活":"live; alive; lively",
  "流":"flow; current; stream",
  "海":"sea; ocean",
  "涉":"wade; cross (water); experience",
  "淡":"bland; insipid; thin; tranquil",
  "深":"deep; profound",
  "淳":"pure; simple; honest; unaffected",
  "淵":"abyss; deep pool; profound",
  "混":"mix; blend; muddy; merged",
  "清":"clear; pure; clean; tranquil",
  "渙":"dissipate; melt away; scatter",
  "渝":"alter; change; mutable",
  "渾":"whole; turbid; murky; entire",
  "湛":"deep; clear; still (of water)",
  "滅":"extinguish; destroy; vanish",
  "滋":"grow; multiply; nourish; more and more",
  "滌":"wash; cleanse; purify",
  "滿":"full; fill; complete",
  "澹":"calm; tranquil; placid (of water)",
  "濁":"muddy; turbid; impure",
  "濟":"aid; help; cross over; succeed in",
  "為":"do; act; become; for the sake of",
  "烹":"cook; boil; fry",
  "焉":"(final particle); where; how; therein",
  "無":"without; not have; non-being",
  "然":"thus; so; right; (suffix '-ly')",
  "熙":"bright; cheerful; bustling (熙熙)",
  "熱":"hot; heat",
  "燕":"swallow (bird); at ease; banquet",
  "營":"manage; encamp; bodily soul (魄)",
  "燿":"shine; dazzle; brilliant",
  "爪":"claw; talon",
  "爭":"contend; strive; quarrel; fight for",
  "父":"father",
  "爽":"refreshing; clear; off-flavor; impair",
  "牖":"window; lattice window",
  "牝":"female (of animals); the feminine",
  "牡":"male (of animals); the masculine",
  "牢":"pen (for animals); feast; sacrificial beast",
  "物":"thing; creature; matter; the myriad things",
  "犬":"dog",
  "狀":"shape; form; condition",
  "狂":"mad; wild; reckless",
  "狎":"familiar with; intimate; despise; trifle with",
  "狗":"dog (芻狗: straw dog used in rituals)",
  "猛":"fierce; brave; violent",
  "猶":"still; like; as if",
  "獨":"alone; solitary; only",
  "獵":"hunt",
  "獸":"beast; animal",
  "玄":"dark; mysterious; profound; the Mystery",
  "玉":"jade",
  "王":"king; royal",
  "珞":"stony; gravel-like (珞珞)",
  "琭":"jade-like; precious (琭琭)",
  "瑕":"flaw; blemish (in jade)",
  "璧":"jade disk (ceremonial)",
  "甘":"sweet; willing; pleasant",
  "甚":"very; excessive; extreme",
  "生":"life; birth; produce; alive",
  "用":"use; employ; usage; function",
  "甫":"begin; (also: a beginning; here: all things)",
  "田":"field; farmland",
  "甲":"armor; first; carapace",
  "畏":"fear; dread; revere",
  "畜":"raise; nurture; livestock; rear",
  "異":"different; strange; unusual",
  "當":"face; correspond to; at (the moment of)",
  "疵":"flaw; defect; blemish",
  "病":"illness; disease; fault; suffer from",
  "登":"ascend; climb; mount",
  "發":"emit; issue forth; start; develop",
  "白":"white; clear; in vain; understand",
  "百":"hundred",
  "皆":"all; every; together",
  "皦":"bright; gleaming; clear",
  "盈":"full; fill; surplus",
  "益":"benefit; increase; gain; advantage",
  "盜":"thief; rob; pilfer",
  "目":"eye",
  "盲":"blind",
  "直":"straight; upright; direct",
  "相":"mutually; each other; appearance; assist",
  "真":"genuine; true; real",
  "矜":"boast; pride oneself; pity; grave",
  "矣":"(perfective sentence-final particle)",
  "知":"know; knowledge; perceive; wisdom",
  "短":"short",
  "石":"stone",
  "示":"show; reveal; display",
  "社":"god of the soil; community; altar (社稷)",
  "祀":"sacrifice; offering; rite",
  "神":"spirit; god; divine; numinous",
  "祥":"auspicious; lucky; ominous (good or ill)",
  "祭":"sacrifice; offering; worship",
  "禍":"calamity; misfortune; disaster",
  "福":"good fortune; blessing; happiness",
  "禮":"ritual; rites; propriety; ceremony",
  "私":"private; personal; selfish",
  "稅":"tax; levy; tribute",
  "稱":"call; name; weigh; commend",
  "稷":"millet; god of grain (社稷: state altars)",
  "稽":"check; examine; investigate",
  "穀":"grain; cereal; nourishment",
  "積":"accumulate; pile up; store",
  "窈":"deep; obscure; subtle; secluded (窈兮)",
  "窪":"hollow; low-lying; depression",
  "窮":"exhaust; poor; ultimate; in extremity",
  "立":"stand; establish; set up",
  "竭":"exhaust; deplete; use up",
  "笑":"laugh; smile",
  "筋":"sinew; muscle; tendon",
  "策":"plan; whip; counting-rod; tally",
  "篤":"sincere; earnest; deeply",
  "籌":"tally; counting-stick; plan",
  "籥":"flute; pipe (橐籥: bellows-pipe)",
  "精":"essence; refined; quintessence; spirit",
  "糞":"dung; manure",
  "紀":"thread; record; principle; epoch",
  "約":"bind; agreement; brief; about",
  "紛":"tangled; confused; profuse",
  "素":"plain; unbleached silk; simple; basic",
  "累":"accumulate; pile up; burden",
  "細":"fine; small; detailed; subtle",
  "終":"end; finish; entire; to the end",
  "結":"knot; tie; bind; conclude",
  "絕":"sever; cut off; absolute; renounce",
  "網":"net; web",
  "綵":"colored silk; figured silk",
  "綿":"continuous; unbroken; soft (綿綿)",
  "繟":"open; expansive; relaxed; serene",
  "繩":"cord; rope; string",
  "纇":"rugged; uneven; flawed",
  "缺":"lack; deficient; incomplete; flaw",
  "罪":"crime; guilt; offense",
  "置":"place; install; set up",
  "美":"beautiful; fine; praise",
  "義":"righteousness; duty; meaning",
  "羸":"weak; frail; emaciated",
  "習":"practice; habit; familiar with",
  "老":"old; aged",
  "者":"(particle: 'one who...'; that which)",
  "而":"and; but; yet; (connective)",
  "耳":"ear",
  "耶":"(question particle, ~'?')",
  "聖":"sage; sagely; holy",
  "聞":"hear; smell; renowned",
  "聲":"sound; voice; tone",
  "聽":"listen; hear; obey",
  "聾":"deaf",
  "肆":"unrestrained; indulge; reckless; market",
  "肖":"resemble; like; mediocre (不肖: 'inferior')",
  "育":"raise; nurture; bear (a child)",
  "能":"can; able; ability; capable",
  "脆":"brittle; fragile; crisp",
  "脫":"escape; shed; remove; slip off",
  "腹":"belly; abdomen",
  "臂":"arm",
  "臣":"minister; subject; vassal",
  "自":"self; from; oneself; naturally",
  "至":"arrive at; utmost; extremely",
  "致":"reach; bring about; deliver; cause",
  "臺":"terrace; platform; tower",
  "與":"and; with; give; participate",
  "興":"rise; flourish; arise; promote",
  "舉":"raise; lift; recommend; bring up",
  "舍":"give up; abandon; lodge; cottage",
  "舟":"boat; ship",
  "色":"color; appearance; sensual beauty",
  "芸":"abundant; flourishing (芸芸)",
  "芻":"straw; fodder (芻狗: straw dog)",
  "若":"if; like; as if; you",
  "草":"grass; plants; rough draft",
  "荊":"bramble; thorn (荊棘)",
  "荒":"vast; wild; barren; uncultivated",
  "莫":"none; do not; nothing",
  "華":"flower; flourish; splendor; surface ornament",
  "萬":"ten thousand; myriad",
  "蒞":"approach; come to; preside over",
  "蓋":"cover; perhaps; presumably; thatch",
  "蔽":"hide; shelter; obscured; worn (worn out)",
  "蕪":"overgrown; weedy; rank; untended",
  "薄":"thin; slight; meager; deficient",
  "藏":"store; hoard; conceal; treasure",
  "虎":"tiger",
  "處":"dwell; abide; place; situation",
  "虛":"empty; void; vacant; humble",
  "號":"call out; cry; designation",
  "虺":"viper; small venomous snake",
  "蛇":"snake; serpent",
  "蜂":"bee; wasp",
  "螫":"sting (of insect)",
  "蠆":"scorpion; venomous insect",
  "衆":"multitude; the masses; many",
  "行":"walk; go; conduct; act; row",
  "衛":"guard; protect; defend",
  "衣":"clothe; clothing; garment",
  "被":"cover; wear; receive; (passive marker)",
  "裂":"split; tear; rip",
  "補":"mend; supplement; supply",
  "褐":"coarse cloth; hempen garment",
  "襲":"inherit; hidden; raid; carry on",
  "要":"essential; want; require; crux",
  "覆":"overturn; cover; reply; subvert",
  "見":"see; appear; be seen",
  "視":"look at; regard; observe",
  "親":"close; intimate; parent; relatives",
  "覽":"survey; view; observe broadly",
  "觀":"observe; behold; contemplate; view",
  "角":"horn; angle; corner",
  "解":"untie; resolve; explain; loosen",
  "言":"speak; say; words",
  "託":"entrust; rely on; commit to",
  "訥":"slow of speech; halting; reticent",
  "詰":"ask; question; interrogate",
  "誠":"sincere; truly; indeed",
  "誰":"who; whom",
  "諱":"taboo; avoid (mention of); shun",
  "諾":"promise; assent; yes (formal)",
  "謀":"plan; scheme; consult",
  "謂":"say; call; mean; tell",
  "識":"know; recognize; perceive",
  "譬":"liken; analogy; for example",
  "譽":"praise; honor; fame",
  "讁":"blame; reproach; censure",
  "谷":"valley; ravine",
  "谿":"mountain stream; ravine",
  "豈":"how (rhetorical); could it be that...?",
  "豐":"abundant; full; rich",
  "象":"image; symbol; resemble; elephant",
  "豫":"hesitant; cautious; pleased; the Yu (state)",
  "貞":"upright; chaste; loyal; correct",
  "負":"carry on back; bear; rely on; turn one's back to",
  "財":"wealth; goods; property",
  "貧":"poor; impoverished",
  "貨":"goods; merchandise; valuables",
  "責":"demand; reproach; responsibility",
  "貴":"honor; value; precious; noble",
  "貸":"lend; loan; bestow",
  "費":"expense; spend; waste",
  "資":"resource; help; means; capital",
  "賊":"bandit; thief; harm; scourge",
  "賓":"guest; submit (as a guest)",
  "賢":"worthy; virtuous; talented",
  "賤":"lowly; cheap; base; humble",
  "質":"substance; quality; plain; pledge",
  "贅":"superfluous; tumor; redundant",
  "赤":"red; bare; sincere; child (赤子: infant)",
  "走":"run; flee; (here: 'sent back')",
  "起":"rise; begin; arise; get up",
  "超":"surpass; leap over; transcend",
  "足":"foot; enough; sufficient",
  "跨":"straddle; step over; stride",
  "踈":"sparse; distant; estranged (=疏)",
  "蹶":"stumble; trip; collapse",
  "躁":"restless; impatient; rash",
  "身":"body; person; oneself",
  "車":"cart; carriage; vehicle",
  "軍":"army; troops",
  "較":"compare; relative; somewhat",
  "載":"carry; bear; load; (initial particle)",
  "輔":"assist; aid; support",
  "輕":"light (in weight); slight; treat lightly",
  "輜":"baggage cart; supply wagon",
  "輟":"stop; cease; break off",
  "輻":"spoke (of a wheel)",
  "輿":"carriage; conveyance; sedan",
  "轂":"hub of a wheel; nave",
  "轍":"wheel-track; rut",
  "辭":"refuse; decline; words; phrase",
  "辯":"argue; debate; dispute; eloquent",
  "辱":"shame; disgrace; humiliate",
  "迎":"meet; welcome; face",
  "迷":"confused; deluded; go astray",
  "迹":"trace; track; footprint",
  "退":"retreat; step back; withdraw",
  "通":"pass through; penetrate; communicate",
  "逝":"depart; pass on; flow away",
  "進":"advance; enter; progress",
  "遂":"thereupon; accomplish; succeed",
  "遇":"meet; encounter; treat",
  "過":"pass; cross; exceed; fault",
  "道":"the Way; Dao; path; speak",
  "達":"reach; penetrate; attain; thorough",
  "遠":"far; distant; remote",
  "遺":"leave behind; lose; remnant",
  "還":"return; come back; pay back",
  "郊":"outskirts; suburbs; borderlands",
  "鄉":"village; rural area; district",
  "鄙":"rustic; vulgar; despise; borderer",
  "鄰":"neighbor; neighboring",
  "配":"match; pair; deserve; consort with",
  "釋":"release; explain; let go of",
  "里":"li (~500m); village",
  "重":"heavy; weighty; gravity; important",
  "金":"gold; metal",
  "銳":"sharp; keen; sharp point",
  "鎮":"suppress; press down; town; quell",
  "鑿":"chisel; bore; hew",
  "長":"long; grow; senior; chief",
  "門":"gate; door; school (of thought)",
  "閉":"close; shut; obstruct",
  "開":"open; begin",
  "間":"between; interval; space; gap",
  "閱":"review; pass through; experience",
  "闔":"close; shut",
  "闚":"peep; spy on; observe through (= 窺)",
  "關":"barrier; pass; close; concern",
  "阿":"slope; fawning; (term of endearment); 'yea'",
  "降":"descend; come down; send down",
  "除":"remove; eliminate; except; clean up",
  "陰":"dark; yin; shaded side",
  "陳":"display; array; old; the Chen (state)",
  "陸":"land; continent; dry land",
  "陽":"bright; yang; sunny side",
  "隅":"corner; angle",
  "隨":"follow; accompany; comply with",
  "隱":"hidden; concealed; secret",
  "隳":"destroy; ruin; demolish",
  "雄":"male (of birds); heroic; masculine",
  "雌":"female (of birds); feminine; yielding",
  "雖":"although; even if",
  "雞":"chicken; fowl",
  "離":"depart; separate; leave",
  "難":"difficult; hard; calamity",
  "雨":"rain",
  "露":"dew; reveal; exposed",
  "靈":"spirit; numinous; efficacious; magical",
  "靜":"still; quiet; tranquility",
  "非":"not; wrong; negate",
  "音":"sound; tone; note",
  "順":"comply; submit; smooth; favorable",
  "頑":"obstinate; dull; stubborn; unyielding",
  "風":"wind; custom; style",
  "飂":"high wind; whirling wind",
  "飄":"gust; whirling wind; floating",
  "食":"eat; food; feed",
  "飢":"hungry; famine",
  "飲":"drink",
  "養":"nourish; raise; rear; cultivate",
  "餌":"bait; food; dainties",
  "餘":"surplus; remainder; excess",
  "首":"head; chief; first; beginning",
  "馬":"horse",
  "馳":"gallop; race; speed",
  "駟":"team of four horses",
  "騁":"gallop; let loose; give free rein",
  "驕":"arrogant; haughty; prideful",
  "驚":"startle; alarm; surprise",
  "驟":"sudden; rapid; gallop",
  "骨":"bone",
  "高":"high; tall; lofty",
  "鬼":"ghost; spirit (of the dead); demon",
  "魄":"earthly soul; bodily spirit (cf. 魂)",
  "魚":"fish",
  "鮮":"fresh; rare; bright (small fish: 小鮮)",
  "鳥":"bird",
  "黑":"black; dark"
};
